# Generated by Django 5.2.7 on 2025-10-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
