# Generated by Django 5.2.7 on 2025-10-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_placeimage_is_main_alter_place_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
