# Generated by Django 5.2.7 on 2025-10-23 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_placeimage_options_placeimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
