# Generated by Django 4.0.6 on 2025-10-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_place_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='place',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
